name: candela_standards
description: "A standard package for Candela Solutions projects."
version: 0.0.2
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  provider: ^6.1.2
  path_provider: ^2.1.5
  material_symbols_icons: ^4.2805.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
